# Generated by Django 4.1.7 on 2023-03-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3'), ('V4', 'V4'), ('V5', 'V5'), ('V6', 'V6')], default='V1', max_length=2)),
                ('team_size', models.IntegerField(default=0)),
                ('count_direct_refs', models.IntegerField(default=0)),
                ('count_level2_refs', models.IntegerField(default=0)),
                ('count_level3_refs', models.IntegerField(default=0)),
                ('count_level4_refs', models.IntegerField(default=0)),
                ('count_level5_refs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralUser',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False, unique=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('referral_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='referral_users.referrallevel')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refs', to='referral_users.referraluser')),
            ],
        ),
    ]
