# Generated by Django 4.1.7 on 2023-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraluser',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
