# Generated by Django 4.1.7 on 2023-03-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_users', '0003_remove_referraluser_referral_level_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referraluser',
            table='referral_users',
        ),
    ]
